# 파드 생성 후 init 컨테이너 생성된다.
# 10초 대기 후에 종료 되면 nginx와 redis가 동시에 뜰것이다.
apiVersion: v1
kind: Pod
metadata:
  name: my-multi-pod
spec:
  initContainers:
    - name: my-initializer
      image: busybox
      command: ['sh', '-c', 'sleep 10']
  containers:
    - name: nginx
      image: nginx:1.24
    - name: redis
      image: redis
